services:
  - type: web
    name: Medical-Pharma
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      # Ajoute ici tes autres variables d'environnement (DB_HOST, DB_DATABASE, etc.) 