services:
  - type: web
    name: Medical-Pharma
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.sipjyvyanccdgwosaibt.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: Abab@@20202025
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stack 